import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// Read GitHub token from local.properties (gitignored). Regenerate on Gradle sync when token changes.
val localProperties = Properties().apply {
    val localFile = rootProject.file("local.properties")
    if (localFile.exists()) {
        localFile.inputStream().use { load(it) }
    }
}

fun secret(propertyKey: String, envKey: String): String =
    (localProperties.getProperty(propertyKey) ?: System.getenv(envKey) ?: "").trim()

val githubToken = secret("GITHUB_TOKEN", "GITHUB_TOKEN")

if (githubToken.isBlank()) {
    logger.warn("GITHUB_TOKEN is missing from local.properties — GitHub API calls will fail until it is set.")
}

val generatedSecretsDir = layout.buildDirectory.dir("generated/dashSecrets/kotlin")

val generateGithubSecrets = tasks.register("generateGithubSecrets") {
    val outputDir = generatedSecretsDir
    inputs.property("githubToken", githubToken)
    outputs.dir(outputDir)
    doLast {
        val tokenValue = inputs.properties["githubToken"].toString()
        fun escapeKotlinString(value: String): String =
            value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")

        val dir = outputDir.get().asFile.resolve("com/ownly/dash/config")
        dir.mkdirs()
        dir.resolve("GithubSecrets.kt").writeText(
            buildString {
                appendLine("// Auto-generated by generateGithubSecrets — do not edit.")
                appendLine("// Token comes from local.properties (GITHUB_TOKEN). Never commit that file.")
                appendLine("package com.ownly.dash.config")
                appendLine()
                appendLine("internal object GithubSecrets {")
                appendLine("    const val TOKEN: String = \"${escapeKotlinString(tokenValue)}\"")
                appendLine("}")
                appendLine()
            },
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                mode = KotlinWebpackConfig.Mode.DEVELOPMENT
                devtool = "eval-source-map"
            }
        }
        binaries.executable()
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx)
            implementation(libs.ktor.client.okhttp)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
            implementation(libs.kotlin.stdlib.wasm.js)
        }
    }
}

configurations {
    all {
        resolutionStrategy {
            force(libs.kotlin.stdlib.wasm.js)
            force(libs.kotlinx.serialization.json)
        }
    }
}

kotlin.sourceSets.getByName("commonMain") {
    kotlin.srcDir(generateGithubSecrets)
}
tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateGithubSecrets)
}

android {
    namespace = "com.ownly.dash"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.ownly.dash"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}
